# Generated by Django 5.1.5 on 2025-01-21 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='valor_planejamento',
            new_name='valor_planejado',
        ),
        migrations.RenameField(
            model_name='conta',
            old_name='apelido',
            new_name='apelido_conta',
        ),
        migrations.RenameField(
            model_name='conta',
            old_name='tipo',
            new_name='tipo_pessoa',
        ),
        migrations.AlterField(
            model_name='conta',
            name='banco',
            field=models.CharField(choices=[('NU', 'Nubank'), ('MP', 'Mercado pago'), ('IN', 'Inter')], max_length=2),
        ),
    ]
