# Generated by Django 5.1.5 on 2025-01-21 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_rename_valor_planejamento_categoria_valor_planejado_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='valor_planejado',
            new_name='valor_planejamento',
        ),
        migrations.RenameField(
            model_name='conta',
            old_name='apelido_conta',
            new_name='apelido',
        ),
        migrations.RenameField(
            model_name='conta',
            old_name='tipo_pessoa',
            new_name='tipo',
        ),
    ]
